<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tahun_xui.UI.ComboInput-R2q</name>
   <tag></tag>
   <elementGuidId>603fede7-319f-40d2-aaeb-1d31222b07a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='xui.UI.ComboInput-R2:q:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;xui\.UI\.ComboInput-R2\:q\:&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c94be89-b412-432d-8a84-368fb98b12bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ComboInput-R2:q:</value>
      <webElementGuid>7239977f-0fe7-4e0e-b601-fe07959dcc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-ui-reset xui-node-button xui-comboinput-r2 xui-ui-btn xui-uibar xui-uigradient xui-nofocus xui-uiborder-radius-br xui-uiborder-noradius-l xui-uiborder-noradius-t     xui-custom</value>
      <webElementGuid>c98c9d38-d07d-4579-b564-4b5ffaf2e558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ComboInput-R2:q:&quot;)</value>
      <webElementGuid>546e6e71-2329-4757-b3d2-2a789da4cec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='xui.UI.ComboInput-R2:q:']</value>
      <webElementGuid>88a1a7d6-7ccf-4728-bac4-5fefb0e28142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ComboInput-SPINBTN:q:']/button[2]</value>
      <webElementGuid>35537f7b-9c3e-4814-a056-0d30c15f32ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun*'])[2]/following::button[4]</value>
      <webElementGuid>92a217e1-af74-4593-ad59-3b5c5c593955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulan*'])[2]/following::button[8]</value>
      <webElementGuid>45d85d03-2959-41ca-8a4d-54cb097d83a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[2]/preceding::button[2]</value>
      <webElementGuid>13d21e3c-8488-4c8c-8f21-52a3f0b6ca62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak'])[1]/preceding::button[3]</value>
      <webElementGuid>5a512f8d-cc27-4214-9f3a-8c6c81f74f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/div[2]/div/div/span/span/span/div[2]/div/div[2]/div/span[2]/span/span[3]/span[3]/button[2]</value>
      <webElementGuid>e610825c-e777-4eb4-9d5e-16655a3fa7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'xui.UI.ComboInput-R2:q:']</value>
      <webElementGuid>d2031ded-f2e0-45c6-ad3b-25ab65470827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
