<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tahun_xui.UI.ComboInput-R2n</name>
   <tag></tag>
   <elementGuidId>2432f061-6ea9-4692-b1a6-c604862c0dee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='xui.UI.ComboInput-R2:n:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;xui\.UI\.ComboInput-R2\:n\:&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cad8f423-be86-4928-8115-e0f06e970951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ComboInput-R2:n:</value>
      <webElementGuid>0c62d56d-8546-43a7-add5-1edb921a23b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-ui-reset xui-node-button xui-comboinput-r2 xui-ui-btn xui-uibar xui-uigradient xui-nofocus xui-uiborder-radius-br xui-uiborder-noradius-l xui-uiborder-noradius-t     xui-custom</value>
      <webElementGuid>19e66af9-a31d-4ba4-9713-b8d3219f7ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ComboInput-R2:n:&quot;)</value>
      <webElementGuid>e93bc038-4ae2-46c1-84e3-57f5e7f9b8bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='xui.UI.ComboInput-R2:n:']</value>
      <webElementGuid>67f65e49-40b1-4e18-955e-490381dde42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ComboInput-SPINBTN:n:']/button[2]</value>
      <webElementGuid>3908ae82-784a-42d4-9d66-68ea57abb917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun*'])[1]/following::button[4]</value>
      <webElementGuid>72457128-ecf2-4a7c-91bd-e28267516d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulan*'])[1]/following::button[8]</value>
      <webElementGuid>0c3a2904-3a7d-4f40-8f7e-88012a7c3329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sudah Lapor ke OJK'])[1]/preceding::button[2]</value>
      <webElementGuid>552939ca-f953-439a-9623-9b917cfdf606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[1]/preceding::button[2]</value>
      <webElementGuid>34cd1e3a-741c-4389-92a2-fbd0a460c82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span[3]/button[2]</value>
      <webElementGuid>a044cc06-ef7e-458d-b20a-889488569b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'xui.UI.ComboInput-R2:n:']</value>
      <webElementGuid>8279b762-f8e0-4d35-9715-d08d3f8ffb70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
