<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SLFC0001 - D01 Perorangan</name>
   <tag></tag>
   <elementGuidId>fa9c33da-91e8-43b0-b085-3a052f61fb8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.List-CAPTION:f:c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SLFC0001 - D01 Perorangan&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b93604b9-14b5-4654-aab6-63dee36951a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.List-CAPTION:f:c</value>
      <webElementGuid>b2271a8f-6d15-4c7e-a51f-45e39a2e4345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-list-caption     xui-custom</value>
      <webElementGuid>5fbd0df1-56e9-45ba-80bd-95dc7c8bb123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SLFC0001 - D01 Perorangan</value>
      <webElementGuid>0b42de50-db9f-4981-a257-c45e7d526354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.List-CAPTION:f:c&quot;)</value>
      <webElementGuid>7d1f96af-6f02-40ce-8f15-5ea02df42dbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.List-CAPTION:f:c']</value>
      <webElementGuid>a5225096-1dae-48ca-8377-7acade5a7029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.List-ITEM:f:c']/span[4]</value>
      <webElementGuid>c9f3aca8-4236-427e-9ecd-54473e4b8c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SLFC0003 - F01 Kredit'])[1]/following::span[8]</value>
      <webElementGuid>964b61e9-19a1-4477-8e88-697f4417bd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEMUA'])[1]/following::span[16]</value>
      <webElementGuid>d42ae17c-a4ac-4dac-8773-51b5d392482d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SLFC0002 - D02 Badan Usaha'])[1]/preceding::span[7]</value>
      <webElementGuid>7e99d8e8-0baf-427f-9a70-ef7682ada822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SLFC0004 - A01 Agunan'])[1]/preceding::span[15]</value>
      <webElementGuid>3b13b13a-b33f-434a-8a53-0c6cc88e249d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SLFC0001 - D01 Perorangan']/parent::*</value>
      <webElementGuid>da33dfc6-45f5-4646-86ad-88c12e1a6ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/span[3]/span[4]</value>
      <webElementGuid>18ca78eb-4729-4a40-a494-b293c8b2c9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.List-CAPTION:f:c' and (text() = 'SLFC0001 - D01 Perorangan' or . = 'SLFC0001 - D01 Perorangan')]</value>
      <webElementGuid>42c108c5-65d3-418e-b304-b32fcbec0480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
