<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_P - PRK_1</name>
   <tag></tag>
   <elementGuidId>9ecc65c3-d081-4d29-b88e-988508fe497e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.List-ITEM:e:d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=&quot;P - PRK&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f2c5d95-cdde-4aa1-9556-ff2b4d76ba08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>05e8e479-55c7-42ec-9c10-5aa1c4e0fa85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.List-ITEM:e:d</value>
      <webElementGuid>83a95542-ddaf-4aa2-bfb3-8260054527a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-span xui-node-span-hover xui-list-item xui-list-item-hover xui-uitembg xui-uitembg-hover xui-uiborder-radius xui-uiborder-radius-hover xui-showfocus xui-showfocus-hover xui-custom xui-custom-hover</value>
      <webElementGuid>4bd4bd0e-e86b-4bad-bdcb-b6222007a369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>P - PRK</value>
      <webElementGuid>9a32bda6-404f-4f38-a995-bb60acf51026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.List-ITEM:e:d&quot;)</value>
      <webElementGuid>b17b7f92-c2e0-40da-b3f2-285bc2d6919b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.List-ITEM:e:d']</value>
      <webElementGuid>5b746d94-8ad3-4634-8e58-954faa3db356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.List-ITEMS:e:']/span[4]</value>
      <webElementGuid>1cd227a2-ab90-41ff-987a-fab83176e870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M - MENURUN'])[6]/following::span[4]</value>
      <webElementGuid>8c6ff2fb-e60e-4a88-a2e9-78aaef900368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D - DISKONTO'])[2]/following::span[12]</value>
      <webElementGuid>a519849a-61c9-47c6-ba39-87a11bc20394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span[4]</value>
      <webElementGuid>5846d671-7eb7-4832-9c3d-3ec95a37cbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.List-ITEM:e:d' and (text() = 'P - PRK' or . = 'P - PRK')]</value>
      <webElementGuid>81997fbe-e8ee-46b8-894d-ecfd1704cd0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
