<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rekening Tidak Memiliki Grace Period_xui_af (1)</name>
   <tag></tag>
   <elementGuidId>6685f1ab-144b-4504-abe5-2900dabe274d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui_af']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xui_af</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#xui_af</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aaf3dce4-b701-4ad9-b311-7297689e9677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-cover xui-custom xui-cover-modal xui-ui-unselectable</value>
      <webElementGuid>22dc9753-0dcd-4ff5-8605-29e5ae7dfa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui_af</value>
      <webElementGuid>611ac970-c3e7-4ee1-ac33-bf6fe3db689f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui_af&quot;)</value>
      <webElementGuid>a2f05702-0850-49cb-bcba-a337ce390ed2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui_af']</value>
      <webElementGuid>ac0833e5-0e61-4e11-8e1e-2027604e33d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='xui_a']/div[8]</value>
      <webElementGuid>afa2db32-242a-48f9-b0c8-b8b18d8a6436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]</value>
      <webElementGuid>f97c0fa6-dc1d-4f79-9d65-7b252d987be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui_af']</value>
      <webElementGuid>1fcae089-eff1-48c3-b596-a3e726d4764a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
