<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rekening Tidak Memiliki Grace Period_xui_af</name>
   <tag></tag>
   <elementGuidId>bf29fd00-42c8-42ec-ad3b-91766e73ba3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#xui_af</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui_af']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#xui_af</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2dae77a-4e6a-4969-912c-85faf832648d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-cover xui-custom xui-cover-modal xui-ui-unselectable</value>
      <webElementGuid>ee42e186-8967-4ebf-9471-79854d9251df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui_af</value>
      <webElementGuid>9d5a5e54-3372-4cc4-bbf5-c1090c83e9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui_af&quot;)</value>
      <webElementGuid>6036706b-28c1-4bd3-8eea-1b26033b5f0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui_af']</value>
      <webElementGuid>d28e8569-a4e3-4c26-ae6b-cb6e49f67f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='xui_a']/div[8]</value>
      <webElementGuid>a076f10e-d818-403d-abdb-09ddbc0abc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]</value>
      <webElementGuid>10747f1e-b310-4570-ac29-e92933d07280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui_af']</value>
      <webElementGuid>9f8963b2-3903-4318-be0d-342e1122f06c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
