<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Data Rekening (1)</name>
   <tag></tag>
   <elementGuidId>bc1ab37b-30ef-4638-a644-07eb7c1e7e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.ButtonViews-IBWRAP:b:b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl_tabLNMA0001 div >> internal:has-text=/^Data Rekening$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4265118-b61e-4109-aba4-9a118f641621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ButtonViews-IBWRAP:b:b</value>
      <webElementGuid>31042417-4511-4224-a51a-a4729bedaad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-buttonviews-ibwrap     xui-custom</value>
      <webElementGuid>03211aa2-ffe2-4b51-950d-87b84540fd66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Rekening</value>
      <webElementGuid>9e01f9f5-a391-4ca9-b227-d3d92881cb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ButtonViews-IBWRAP:b:b&quot;)</value>
      <webElementGuid>997dff1f-4644-49c0-92c5-60a15b5a4d22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.ButtonViews-IBWRAP:b:b']</value>
      <webElementGuid>a8b3b8a4-da99-4fd6-ac6e-0fcd78071346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ButtonViews-HANDLE:b:b']/div</value>
      <webElementGuid>5ee065eb-ff9b-4a97-b365-08d431bd9663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Nasabah'])[2]/following::div[1]</value>
      <webElementGuid>9bbf82bd-1fe0-4703-8212-8e676d0ec1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Nasabah'])[1]/following::div[4]</value>
      <webElementGuid>37ed53a9-2158-4dde-a534-086b12ba93d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Grace Period'])[1]/preceding::div[1]</value>
      <webElementGuid>986b72cf-c790-4aef-b5e5-70205a295e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]/span/span/span/div</value>
      <webElementGuid>e5aaa643-e8f4-4f54-be52-eff895b5a38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.ButtonViews-IBWRAP:b:b' and (text() = 'Data Rekening' or . = 'Data Rekening')]</value>
      <webElementGuid>76d56cda-5750-47ad-9d90-bb168843e0fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
