<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Data Biaya (1)</name>
   <tag></tag>
   <elementGuidId>cc8ba89c-aabf-4e4d-9066-6f23a4bebf4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.ButtonViews-IBWRAP:b:e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl_tabLNMA0001 div >> internal:has-text=/^Data Biaya$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bb6fcde-ec38-4376-8347-f257aa0f97a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ButtonViews-IBWRAP:b:e</value>
      <webElementGuid>b0128dae-4f51-4758-a2e4-f2ace0f98a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-buttonviews-ibwrap     xui-custom</value>
      <webElementGuid>a674d8ed-7579-4de8-9ec5-6cac47196521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Biaya</value>
      <webElementGuid>fc2d8c8f-378b-4852-81bb-b2d254a9dc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ButtonViews-IBWRAP:b:e&quot;)</value>
      <webElementGuid>c56cf1e9-b3a7-48ca-a8ab-aa26c7f3cb73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.ButtonViews-IBWRAP:b:e']</value>
      <webElementGuid>5b63cd3d-c1bc-4583-9294-eb991b6fd8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ButtonViews-HANDLE:b:e']/div</value>
      <webElementGuid>62b17245-e939-4efa-b672-3f3a5cd73633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Jadwal Angsuran'])[2]/following::div[1]</value>
      <webElementGuid>0a78cfdb-2bb4-4dea-91b2-26cb01937451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Grace Period'])[1]/following::div[2]</value>
      <webElementGuid>651052d1-0e4b-42a8-9b9f-a90369b2299b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Amortisasi EIR'])[1]/preceding::div[1]</value>
      <webElementGuid>5d8d249a-cd39-4a89-ac76-cf37b755853a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/span/span/span/div</value>
      <webElementGuid>e6567252-84b0-4147-bf74-f8b12440c26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.ButtonViews-IBWRAP:b:e' and (text() = 'Data Biaya' or . = 'Data Biaya')]</value>
      <webElementGuid>cb23e8b2-f7ef-48f7-ad74-0eaf350e857d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
