<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Data Amortisasi EIR (1)</name>
   <tag></tag>
   <elementGuidId>9a1c92ca-e2af-406e-8f67-0f7c775f2e58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.ButtonViews-IBWRAP:b:f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl_tabLNMA0001 div >> internal:has-text=/^Data Amortisasi EIR$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f9b5d33-b1bd-4338-8506-1f41a6af1e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ButtonViews-IBWRAP:b:f</value>
      <webElementGuid>29aed87e-6757-4f14-8f15-7dfa25cdff73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-buttonviews-ibwrap     xui-custom</value>
      <webElementGuid>a1557286-4310-4c41-977f-b5f43168c72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Amortisasi EIR</value>
      <webElementGuid>8cfc51e7-e90b-4bad-8db5-d2848e63da6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ButtonViews-IBWRAP:b:f&quot;)</value>
      <webElementGuid>6726d45a-a454-483f-89ec-f29d26d8761a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.ButtonViews-IBWRAP:b:f']</value>
      <webElementGuid>34d153d9-a8f1-417e-b309-e43019971d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ButtonViews-HANDLE:b:f']/div</value>
      <webElementGuid>eb35a144-57cd-4843-a812-608db8deab3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Biaya'])[2]/following::div[1]</value>
      <webElementGuid>4b811553-0d34-4398-89c0-5cba2ae6df1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Jadwal Angsuran'])[1]/following::div[2]</value>
      <webElementGuid>a43070ea-cca7-4306-8814-43ed1aa4d297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Lapbul Apolo'])[1]/preceding::div[1]</value>
      <webElementGuid>d9a55fa5-a270-4d50-826a-60a89f69967b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/span/span/span/div</value>
      <webElementGuid>68474c4e-35fb-426d-8c99-12e4c0ba9e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.ButtonViews-IBWRAP:b:f' and (text() = 'Data Amortisasi EIR' or . = 'Data Amortisasi EIR')]</value>
      <webElementGuid>a03875f4-3c45-42eb-827b-0ff673d7e0ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
