<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Data SLIK</name>
   <tag></tag>
   <elementGuidId>95fd6c62-dd43-43ec-b2a6-9f5b23cd407a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.ButtonViews-IBWRAP:b:h']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl_tabLNMA0004 div >> internal:has-text=/^Data SLIK$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3958cae5-75dd-423d-af64-26db734b3d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ButtonViews-IBWRAP:b:h</value>
      <webElementGuid>e6969c75-fb85-4ae2-9a29-79b96552ecd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-buttonviews-ibwrap     xui-custom</value>
      <webElementGuid>4a164d95-788f-40fa-b084-d3148e895af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data SLIK</value>
      <webElementGuid>7c405d29-bd4a-4e7d-92f5-64895d32c610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ButtonViews-IBWRAP:b:h&quot;)</value>
      <webElementGuid>8a8b2fd7-91f1-4e33-9f97-a2dd4df5a368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.ButtonViews-IBWRAP:b:h']</value>
      <webElementGuid>e2dd0cb8-8b0f-4625-b4aa-8df26953fd01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ButtonViews-HANDLE:b:h']/div</value>
      <webElementGuid>675c8077-21f1-4632-a6e2-f7debd7c72ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Lapbul Apolo'])[2]/following::div[1]</value>
      <webElementGuid>66702281-afc5-497b-8e6f-d6af3c3023ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Amortisasi EIR'])[1]/following::div[2]</value>
      <webElementGuid>6f197dbd-9f84-4cc4-a300-1e9d297d12f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Non Finansial'])[1]/preceding::div[1]</value>
      <webElementGuid>8d25bb63-4f02-4425-a476-f395a21c9344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[8]/span/span/span/div</value>
      <webElementGuid>2c232433-c5ca-43fc-b497-abede4593079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.ButtonViews-IBWRAP:b:h' and (text() = 'Data SLIK' or . = 'Data SLIK')]</value>
      <webElementGuid>2bd69ff1-21e3-4afb-866b-7d022e0decf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
