<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(id(, , xui_o, , ))_xui_o</name>
   <tag></tag>
   <elementGuidId>feba071c-414a-4e0b-a35a-97286c6127e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui_o']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xui_o</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#xui_o</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59a6f2c9-b539-48f2-b65c-8c2b64d12dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-cover xui-custom xui-cover-modal xui-ui-unselectable</value>
      <webElementGuid>d494ecc7-39e8-47c3-a7f7-581a6d23f806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui_o</value>
      <webElementGuid>e424db13-b178-4dbb-a868-5f7d6ddb209f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui_o&quot;)</value>
      <webElementGuid>5a625623-6f96-4dbf-8532-3f0dc2c498b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui_o']</value>
      <webElementGuid>829ce716-cc6f-4972-9111-aa03ebd79792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='xui_a']/div[6]</value>
      <webElementGuid>879199dc-2b84-4a93-b15a-9476f394d1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>65971c43-6ff7-4bd7-ad69-c80583df116c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui_o']</value>
      <webElementGuid>d1a867ce-6d28-4380-918c-09ac16b1e51a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
