<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Data Biaya</name>
   <tag></tag>
   <elementGuidId>52a5eeba-78c8-4478-a678-526f11acd791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.ButtonViews-IBWRAP:b:e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Data Biaya$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f3d492d-8eb5-4d83-b9b0-9a0a06215c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ButtonViews-IBWRAP:b:e</value>
      <webElementGuid>8dab3857-14f0-43e3-a8de-c6c9d01b4fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-buttonviews-ibwrap     xui-custom</value>
      <webElementGuid>dd7cc013-07da-417e-b8b6-1a7ac16a98ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Biaya</value>
      <webElementGuid>30a5c2a1-06b6-49c2-a290-919513d7350e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ButtonViews-IBWRAP:b:e&quot;)</value>
      <webElementGuid>eda745c0-402b-4277-9aa3-3452b81c3916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.ButtonViews-IBWRAP:b:e']</value>
      <webElementGuid>5aba1c17-9acb-4da5-91ed-7239815a85ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ButtonViews-HANDLE:b:e']/div</value>
      <webElementGuid>46bbbdb9-02a7-4140-9595-d061aa1b2457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Jadwal Angsuran Non Rutin'])[2]/following::div[1]</value>
      <webElementGuid>a9eea00e-1404-4029-b3b2-d8da89b01cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Grace Period'])[1]/following::div[2]</value>
      <webElementGuid>ebcb73d9-c260-45fd-a718-912eb246a67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Amortisasi EIR'])[1]/preceding::div[1]</value>
      <webElementGuid>a395dd98-87e5-4ec0-b52c-1ab097b32a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/span/span/span/div</value>
      <webElementGuid>a8b93691-15bf-4c82-9f0b-5c58055578e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.ButtonViews-IBWRAP:b:e' and (text() = 'Data Biaya' or . = 'Data Biaya')]</value>
      <webElementGuid>5c27c84f-1ff6-4567-bf81-a53636431711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
