<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Loading (1)</name>
   <tag></tag>
   <elementGuidId>6f5a3d68-81bc-4e03-bd03-8dc2c1bbc483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:t:']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.xui-node.xui-node-div.xuicon.xui-icon-loading.xui-cover.xui-custom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Loading...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6825217-015c-4224-9aa8-6395c2814f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xuicon xui-icon-loading xui-cover xui-custom</value>
      <webElementGuid>046138c9-972e-450f-affb-04dff3c40ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>b589e389-1ba9-4197-b91b-5053682eb939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:t:&quot;)/button[@class=&quot;xui-node xui-node-div xuicon xui-icon-loading xui-cover xui-custom&quot;]</value>
      <webElementGuid>4726664d-e4ec-4f14-bdad-5d82d7eb7224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:t:']/button</value>
      <webElementGuid>5639bf86-48d8-44fe-982e-08f3e8c6f701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Komentar'])[1]/following::button[1]</value>
      <webElementGuid>e09fc3b0-cde0-406c-9b27-c8724ae5ddd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Komentar Terakhir'])[1]/following::button[1]</value>
      <webElementGuid>fe9a0be3-30f0-468b-9316-22b05ba05b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LNMA0035'])[1]/preceding::button[1]</value>
      <webElementGuid>52905d6f-de1d-4888-8e10-3f4290cc8495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>c6b4d9a9-8b7c-40f1-aade-993b371edef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Loading...' or . = 'Loading...')]</value>
      <webElementGuid>9e83f139-69ba-4fa3-80fa-1791d31c103b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
