<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DATA DETAIL</name>
   <tag></tag>
   <elementGuidId>b6829116-d220-4725-be2c-173c8d1774cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Panel-CAPTION:e:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;DATA DETAIL *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b3c24bf-b221-4308-b633-e696829677fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9f9de502-9ad2-4e0f-9b63-09528dc73f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Panel-CAPTION:e:</value>
      <webElementGuid>280f086f-f9c4-4858-a2e0-2319c1f19280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-panel-caption xui-title-node     xui-custom</value>
      <webElementGuid>23aa75fb-99fe-4059-9532-c27032a531a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DATA DETAIL *</value>
      <webElementGuid>a83ecd59-fc83-4d60-9a66-655d00fc904d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Panel-CAPTION:e:&quot;)</value>
      <webElementGuid>925c10f8-a1f5-4e0c-aeaa-271859fb4516</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Panel-CAPTION:e:']</value>
      <webElementGuid>cab38a82-3e57-46e7-adaf-2f8cc6a27085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Panel-BARCMDL:e:']/span[4]</value>
      <webElementGuid>4bd1bd7b-aecd-4571-a86f-1a8cd3bdee03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Paripasu'])[1]/following::span[16]</value>
      <webElementGuid>3e7743f9-6fda-43ad-8ea1-ddd0e4abd9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIDAK'])[2]/following::span[19]</value>
      <webElementGuid>d77df3d9-6fb6-4296-ac41-28323aa82df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA APPRAISAL'])[1]/preceding::span[19]</value>
      <webElementGuid>b11f7586-22cf-4275-b90a-a2d0e5c12b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA PARIPASU'])[1]/preceding::span[38]</value>
      <webElementGuid>76265e9f-9878-40bd-9599-47ca7361a237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DATA DETAIL *']/parent::*</value>
      <webElementGuid>4931d2aa-be34-4eea-a317-a046407b172a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/span[4]</value>
      <webElementGuid>8330bd95-0c97-47ab-82d3-aba348b45e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Panel-CAPTION:e:' and (text() = 'DATA DETAIL *' or . = 'DATA DETAIL *')]</value>
      <webElementGuid>e5f77525-971e-4a0b-b509-f47a4ddda511</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
