<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PEMELIHARAAN STOP KEWAJIBAN PINJAMANcf__f2ccdf</name>
   <tag></tag>
   <elementGuidId>e49539b1-c228-4187-be6d-b5e1f726926b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:t:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;PEMELIHARAAN STOP KEWAJIBAN PINJAMANcf_mast_idln_mast_idcf_mast_idsourceid_templ&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c62f11f9-3a1e-4249-a5cb-9a7594f9b4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>efdb064e-0663-40bf-8b01-8625047cbc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:t:</value>
      <webElementGuid>3e87ede5-8e32-45c8-8888-5d82a271ee76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer xui-ui-ctrl xui-ui-selectable xui-custom xui-css-noscrollx</value>
      <webElementGuid>2d57c818-15ee-43c1-8a35-078af13a99b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PEMELIHARAAN STOP KEWAJIBAN PINJAMANcf_mast_idln_mast_idcf_mast_idsourceid_templast_updatedNama Nasabah / No Rekening*300400001510301400001411BatalSimpanDATA PEMELIHARAAN STOP KEWAJIBAN PINJAMANProduk PinjamanProduk PinjamanKantor Pemilik RekeningKantor Pemilik RekeningNama NasabahNama Pada RekeningNomor IdentitasNomor RekeningKolektabilitasKolektabilitasPlafondBaki DebetTgl Tgk PokokTgl Tgk BungaTunggakan PokokTunggakan BungaDenda PokokDenda BungaTunggakan PokokAlasan Stop Kewajiban*Catatan</value>
      <webElementGuid>8a21b3ee-cb84-4268-9308-d25fbed3c253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:t:&quot;)</value>
      <webElementGuid>7ad844bd-a11a-4332-9247-4b70fcc44c32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:t:']</value>
      <webElementGuid>50a62cf9-dcb8-459c-b3eb-8a5adec36d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Block-PANEL:r:']/div</value>
      <webElementGuid>e7693255-62aa-4fa8-a812-6accfc50a5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PEMELIHARAAN STOP KEWAJIBAN PINJAMAN'])[1]/following::div[8]</value>
      <webElementGuid>a9d48ce4-7ee9-42d5-94e2-50786f37e583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='c'])[1]/following::div[11]</value>
      <webElementGuid>b5ee9a72-6eae-4dab-9328-8f00b7caf99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span/span/div[2]/div</value>
      <webElementGuid>dc0e6b7e-112d-443c-aa06-7de0abb4d79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:t:' and (text() = 'PEMELIHARAAN STOP KEWAJIBAN PINJAMANcf_mast_idln_mast_idcf_mast_idsourceid_templast_updatedNama Nasabah / No Rekening*300400001510301400001411BatalSimpanDATA PEMELIHARAAN STOP KEWAJIBAN PINJAMANProduk PinjamanProduk PinjamanKantor Pemilik RekeningKantor Pemilik RekeningNama NasabahNama Pada RekeningNomor IdentitasNomor RekeningKolektabilitasKolektabilitasPlafondBaki DebetTgl Tgk PokokTgl Tgk BungaTunggakan PokokTunggakan BungaDenda PokokDenda BungaTunggakan PokokAlasan Stop Kewajiban*Catatan' or . = 'PEMELIHARAAN STOP KEWAJIBAN PINJAMANcf_mast_idln_mast_idcf_mast_idsourceid_templast_updatedNama Nasabah / No Rekening*300400001510301400001411BatalSimpanDATA PEMELIHARAAN STOP KEWAJIBAN PINJAMANProduk PinjamanProduk PinjamanKantor Pemilik RekeningKantor Pemilik RekeningNama NasabahNama Pada RekeningNomor IdentitasNomor RekeningKolektabilitasKolektabilitasPlafondBaki DebetTgl Tgk PokokTgl Tgk BungaTunggakan PokokTunggakan BungaDenda PokokDenda BungaTunggakan PokokAlasan Stop Kewajiban*Catatan')]</value>
      <webElementGuid>8625b1f2-b114-46f0-88e9-fe0437d50c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
