<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PEMELIHARAAN AGUNAN</name>
   <tag></tag>
   <elementGuidId>0dfff41c-8d94-4eb5-adf3-95afa8e4541a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Dialog-CAPTION:h:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;PEMELIHARAAN AGUNAN&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a898e055-6a5e-4369-b11b-338e167fd843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fa7bb21c-8422-46ae-9d77-ceb994de948f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Dialog-CAPTION:h:</value>
      <webElementGuid>b1142653-60c9-4b4d-95bd-f64c02714a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-dialog-caption xui-title-node     xui-custom</value>
      <webElementGuid>75d2e2d1-5307-4413-830f-1ad33dfe1566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PEMELIHARAAN AGUNAN</value>
      <webElementGuid>dcc0510e-f3d6-482d-85c6-223de90b1630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Dialog-CAPTION:h:&quot;)</value>
      <webElementGuid>2a2d0caa-2295-4486-a15f-23ee908aff73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Dialog-CAPTION:h:']</value>
      <webElementGuid>47c234f7-8897-4646-8875-c857f50cdfb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Dialog-BARCMDL:h:']/span[4]</value>
      <webElementGuid>8c875e66-820a-4212-b34a-2619a99e8347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='c'])[1]/following::span[20]</value>
      <webElementGuid>67cfb46e-837f-4f7a-989e-780818424ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::span[23]</value>
      <webElementGuid>bf77ee1e-ffa1-44b9-99a5-1ddaa12cd5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian CIF*'])[1]/preceding::span[14]</value>
      <webElementGuid>7b260459-2763-4ed6-9ae8-72d8dd479a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::span[45]</value>
      <webElementGuid>5e7f1cdc-bbbe-46dd-a1cf-e4eba166ad59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PEMELIHARAAN AGUNAN']/parent::*</value>
      <webElementGuid>8cd29200-a0c3-4d40-a338-70ddd01c05d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/div/div/span[4]</value>
      <webElementGuid>290a0b45-ce79-4c12-b1d7-e8cc4ca191ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Dialog-CAPTION:h:' and (text() = 'PEMELIHARAAN AGUNAN' or . = 'PEMELIHARAAN AGUNAN')]</value>
      <webElementGuid>f49ae1f1-d35f-4b32-b0bc-edc68c2ff852</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
