<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TBD - TABUNGAN DAN DEPOSITO</name>
   <tag></tag>
   <elementGuidId>798b3440-a781-42a9-9cc9-87e3bcece0fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.List-CAPTION:e:e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;TBD - TABUNGAN DAN DEPOSITO&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fdb4ed8e-efe6-4ca4-b97d-2af048e886a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.List-CAPTION:e:e</value>
      <webElementGuid>7e8453bb-11e7-4ab0-8562-8880ffaaaf49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-list-caption     xui-custom</value>
      <webElementGuid>5db15b13-b141-4b8c-a953-b2976336bc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TBD - TABUNGAN DAN DEPOSITO</value>
      <webElementGuid>c95b2418-538f-4207-a83b-e7562844a88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.List-CAPTION:e:e&quot;)</value>
      <webElementGuid>ea04e1b8-628c-4515-b666-9822c457b14b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.List-CAPTION:e:e']</value>
      <webElementGuid>0eadcd26-4dda-4361-bc95-efde720ea51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.List-ITEM:e:e']/span[4]</value>
      <webElementGuid>55ef4017-4f73-4576-bbb3-c98f59e5c5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SRT - SURAT BERHARGA'])[1]/following::span[8]</value>
      <webElementGuid>48391ec6-2dfa-40f1-bb9c-92e724112572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIN - LAINNYA'])[1]/following::span[16]</value>
      <webElementGuid>e7cc816e-8856-4f2a-a9a8-c8c9af4e6a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TNB - TANAH BANGUNAN'])[1]/preceding::span[7]</value>
      <webElementGuid>d980a14a-a19a-4e22-87e7-7d44fc3c6f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TS2 - TESANDREW22'])[1]/preceding::span[15]</value>
      <webElementGuid>7e8effcf-43d0-4635-b29d-a901e5d281ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TBD - TABUNGAN DAN DEPOSITO']/parent::*</value>
      <webElementGuid>d47d3583-87d3-4a99-bf2c-83998c40e5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/span[5]/span[4]</value>
      <webElementGuid>3f12b43d-ff69-4430-9858-6f2a465a61cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.List-CAPTION:e:e' and (text() = 'TBD - TABUNGAN DAN DEPOSITO' or . = 'TBD - TABUNGAN DAN DEPOSITO')]</value>
      <webElementGuid>96a3016d-c6d4-4521-adaf-1ead1e8ce230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
